import test from "node:test";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { WorkspaceAgentEngine, WorkspaceAgentStateStore } from "./agent-engine.mjs";

test("workspace agent engine resolves context and records task state", async () => {
  const root = await fixtureWorkspace();
  // FakeAgentAdapter is still passed as compat for event routing tests,
  // but session/chat routing now goes through WorkspaceChatBackend (standalone-first).
  const adapter = new FakeAgentAdapter();
  const engine = new WorkspaceAgentEngine({ workspaceRoot: root }, adapter);

  const session = await engine.createSession({
    provider: "local",
    model: "test-model",
    accessMode: "confirm",
    reasoningEffort: "medium"
  });
  // Local session IDs are generated by WorkspaceChatBackend as ws-sess-*
  assert.match(session.sessionId, /^ws-sess-/);
  assert.equal(session.engine, "workspace-agent");

  // submitPrompt throws when no provider is configured (setupRequired).
  // The engine still records a task before throwing.
  let taskId;
  try {
    await engine.submitPrompt({
      sessionId: session.sessionId,
      message: "이 노트 설명해줘",
      contextRequest: {
        scopeType: "note",
        scopePath: "Notes/a.md",
        activePath: "Notes/a.md"
      }
    });
    assert.fail("Expected submitPrompt to throw when no provider is configured.");
  } catch (err) {
    assert.match(err.message, /provider/i);
  }

  // Find the task that was recorded before the error was thrown.
  const taskDir = path.join(root, ".ai-workspace", "tasks");
  const allFiles = await fs.readdir(taskDir);
  const taskFiles = allFiles.filter(f => f.startsWith("task-") && f.endsWith(".json"));
  assert.equal(taskFiles.length > 0, true);
  const task = JSON.parse(await fs.readFile(path.join(taskDir, taskFiles[0]), "utf8"));
  assert.equal(task.sessionId, session.sessionId);
  assert.equal(task.status, "failed");

  const events = await fs.readFile(path.join(root, ".ai-workspace", "sessions", "events.jsonl"), "utf8");
  assert.match(events, /session.create/);
});

test("workspace agent engine records live tool events under workspace state", async () => {
  const root = await fixtureWorkspace();
  const adapter = new FakeAgentAdapter();
  const engine = new WorkspaceAgentEngine({ workspaceRoot: root }, adapter);

  adapter.emit("event", {
    type: "tool.start",
    sessionId: "stored-1",
    text: "search_files"
  });
  await engine.flush();

  const allEvents = await fs.readFile(path.join(root, ".ai-workspace", "tool-logs", "live-events.jsonl"), "utf8");
  const toolEvents = await fs.readFile(path.join(root, ".ai-workspace", "tool-logs", "tool-events.jsonl"), "utf8");
  assert.match(allEvents, /workspace-agent/);
  assert.match(toolEvents, /tool.start/);
  assert.match(toolEvents, /search_files/);
});

test("workspace agent state creates the unified state directory shape", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agent-state-"));
  await new WorkspaceAgentStateStore(root).ensure();
  for (const folder of ["sessions", "tasks", "memory", "approvals", "decisions", "tool-logs", "diffs", "index"]) {
    const stat = await fs.stat(path.join(root, ".ai-workspace", folder));
    assert.equal(stat.isDirectory(), true);
  }
});

test("workspace agent state lists task summaries", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agent-state-list-"));
  const state = new WorkspaceAgentStateStore(root);
  const codeTask = await state.startTask({
    type: "code",
    status: "started",
    message: "change renderer",
    scopePath: "Code/demo"
  });
  await state.finishTask(codeTask.id, {
    status: "inspected",
    plan: { summary: "Code task prepared." }
  });
  await state.startTask({
    type: "chat",
    message: "hello"
  });

  const listed = await state.listTasks({ type: "code" });
  assert.equal(listed.tasks.length, 1);
  assert.equal(listed.tasks[0].id, codeTask.id);
  assert.equal(listed.tasks[0].summary, "Code task prepared.");
  assert.equal(listed.tasks[0].scopePath, "Code/demo");
});

test("workspace agent state records and resolves approval inbox items", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agent-state-approvals-"));
  const state = new WorkspaceAgentStateStore(root);
  const approval = await state.recordApprovalRequest({
    category: "code.patch.apply",
    taskId: "task-1",
    proposalId: "patch-1",
    scopePath: "Code/demo",
    summary: "Apply patch"
  });

  assert.match(approval.id, /^approval-/);
  assert.equal(approval.status, "pending");

  const listed = await state.listApprovals({ status: "pending" });
  assert.equal(listed.approvals.length, 1);
  assert.equal(listed.approvals[0].id, approval.id);

  const resolved = await state.resolveApproval(approval.id, {
    approved: false,
    reason: "No thanks."
  });
  assert.equal(resolved.status, "rejected");
  assert.equal(resolved.reason, "No thanks.");

  const pending = await state.listApprovals({ status: "pending" });
  assert.equal(pending.approvals.length, 0);
});

test("workspace agent state config read and write", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agent-state-config-"));
  const state = new WorkspaceAgentStateStore(root);

  const defaults = await state.readConfig();
  assert.equal(defaults.model?.provider, "anthropic");
  assert.equal(defaults.model?.default, "anthropic/claude-3-5-sonnet");
  assert.deepEqual(defaults.credentials, []);

  defaults.model.default = "openai/gpt-4o";
  defaults.model.provider = "openai";
  defaults.credentials.push({
    id: "cred-test",
    provider: "openai",
    apiKey: "sk-openai-key-123",
    label: "OpenAI Key"
  });

  await state.writeConfig(defaults);

  const updated = await state.readConfig();
  assert.equal(updated.model?.default, "openai/gpt-4o");
  assert.equal(updated.model?.provider, "openai");
  assert.equal(updated.credentials.length, 1);
  assert.equal(updated.credentials[0].apiKey, "sk-openai-key-123");
});

class FakeAgentAdapter extends EventEmitter {
  constructor() {
    super();
    this.name = "fake-agent";
    this.lastPrompt = null;
  }

  async connect() {}

  async createSession() {
    return {
      sessionId: "stored-1",
      runtimeSessionId: "runtime-1",
      source: "fake"
    };
  }

  async resumeSession() {
    return "runtime-1";
  }

  async submitPrompt(params) {
    this.lastPrompt = params;
    return {
      ok: true,
      sessionId: params.sessionId,
      runtimeSessionId: "runtime-1"
    };
  }

  async respondToApproval(params) {
    return {
      ok: true,
      sessionId: params.sessionId,
      runtimeSessionId: "runtime-1",
      choice: params.approved === false ? "deny" : "once"
    };
  }

  async setAccessMode() {}

  async setReasoning() {}

  close() {}
}

async function fixtureWorkspace() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agent-engine-"));
  await fs.mkdir(path.join(root, "Notes"), { recursive: true });
  await fs.writeFile(path.join(root, "Notes", "a.md"), "# Alpha note\n\nHello.", "utf8");
  return root;
}
